### ISSUE TITLE
not showing autocomplete popup

### ISSUE THREAD

**Issue by tolorr** [SublimeCodeIntel/SublimeCodeIntel#271]
Hello!

Today my sublimecodeintel has been updated. Now, not show the autocomplete popup!

I've been several hours trying to fix it, but i can't.

**Comment by ElijahAIsaac** [comment]
@Kronuz, does this also apply to ST3running under Windows 8.2?

"I believe the problem you are describing is caused by the sublime_auto_complete setting. Please open your SublimeCodeIntel User Settings (in the menu, Preferences -> Packages -> SublimeCodeIntel -> User Settings) then add: "sublime_auto_complete": true and see if that fixes the problem."

**Comment by keremkulak** [comment]
80$ for shit, kidding right?
