### ISSUE TITLE
Is this project dead? 

### ISSUE THREAD

**Issue by dvcrn** [SublimeCodeIntel/SublimeCodeIntel#542]
As the title says, is SublimeCodeintel dead or still active? The last release has been over half a year ago. What is the direction this project is going to take?

**Comment by Kronuz** [comment]
No, it isn't dead. It just has a slow release process. Since much of updates and changes happen in the Komodo Editor side, we just wait some time and then release.

Next major SublimeCodeIntel version will use the CodeIntel Python package (at PyPI) as an external command line dependency (where all the complexity be handled) and the Sublime Text plugin will be very small in comparison; it'll just be a tiny wrapper to it in the form of a small plugin.

**Comment by dvcrn** [comment]
Oh ok, thanks for clearing that up!
