### ISSUE TITLE
Error reading data from OOP CodeIntel: Failed to read from socket

### ISSUE THREAD

**Issue by matianhe** [SublimeCodeIntel/SublimeCodeIntel#685]
sublime text console : `Error reading data from OOP CodeIntel: Failed to read from socket`

**Comment by rcordeau** [comment]
I had the same issue. I had CodeIntel installed for both 2.7 and 3.7, and the 3.7 installation had some issues. So I uninstalled CodeIntel from Python 3.7 and it seemed to fix the issue.

**Comment by TobiOkanlawon** [comment]
Hello, which python version does SublimeCodeIntel work with?

**Comment by rannuo** [comment]
I had the same issue.

**Comment by ian-perry-ironnet** [comment]
Same issue

**Comment by bubjavier** [comment]
had same issue, and realized I pip installed it using python3 instead of just python (v2).
`python3 -m pip install -U CodeIntel`

just pip uninstall it,
`python3 -m pip uninstall CodeIntel`
then install it with python2:
`python -m pip install -U CodeIntel`
make sure remove codeintel's workspace dir:
`rm -rf ~/.codeintel`
